<?php 

$arr = [
	["id"=>'twelve',"bigImage"=>'<img src="./assets/images/pic/r3-big1.jpg" alt="">',"smallImage"=>'<dd class="active"><img src="./assets/images/pic/r3-small1.jpg" alt=""></dd>',"text"=>'<div class="text"><h2>暴风魔镜小M虚拟现实智能VR眼镜 基础版</h2><h3>IMAX巨屏影院 360度全影视频</h3><div class="price"><em>￥</em>&nbsp;<span class="num">49</span></div></div>'],
	["id"=>'four',"bigImage"=>'<img src="./assets/images/pic/r1-big1.jpg" alt=""><img class="img2" src="./assets/images/pic/r1-big2.jpg" alt="">',"smallImage"=>'<dd class="active"><img src="./assets/images/pic/r1-small1.jpg" alt=""></dd><dd><img src="./assets/images/pic/r1-small2.jpg" alt=""></dd>',"text"=>'<h2>纽曼 NM-VR30 虚拟现实智能VR眼镜</h2><h3>佩戴舒适人性化设计</h3><div class="price"><em>￥</em>&nbsp;<span class="num">59</span>&nbsp;<span class="start">起</span></div>'],
	["id"=>'three',"bigImage"=>'<img src="./assets/images/pic/r9-big1.jpg" alt="">',"smallImage"=>'<dd class="active"><img src="./assets/images/pic/r9-small1.jpg" alt=""></dd>',"text"=>'<h2>乐心手环MAMBO 大麦版</h2><h3>微信互联 来电提醒 即时消息 睡眠监测 防水</h3><div class="price"><span class="time">限时特惠</span>&nbsp;<em>￥</em>&nbsp;<span class="num">89</span>'],
	["id"=>'five',"bigImage"=>'<a href="detail.html"><img src="./assets/images/pic/r5-big1.jpg" alt=""></a>',"smallImage"=>'<dd class="active"><img src="./assets/images/pic/r5-small1.jpg" alt=""></dd>',"text"=>'<h2>纽曼智能眼镜虚拟现实3D眼镜NM-VR01</h2><h4>买即送手柄 军工工艺 舒适透气升级 防疲劳</h4><div class="price"><em>￥</em>&nbsp;<span class="num">99</span></div>'],
	["id"=>'two',"bigImage"=>'<img src="./assets/images/pic/r2-big1.jpg" alt=""><img class="img2" src="./assets/images/pic/r2-big2.jpg" alt=""><img class="img2" src="./assets/images/pic/r2-big3.jpg" alt=""><img class="img2" src="./assets/images/pic/r2-big4.jpg" alt="">',"smallImage"=>'<dd class="active"><img src="./assets/images/pic/r2-small1.jpg" alt=""></dd><dd><img src="./assets/images/pic/r2-small2.jpg" alt=""></dd><dd><img src="./assets/images/pic/r2-small3.jpg" alt=""></dd><dd><img src="./assets/images/pic/r2-small4.jpg" alt=""></dd>',"text"=>'<h2>乐心心率手环MAMBO2</h2><h4>24 小时心率监测 跑步轨迹记录</h4><div class="price"><span class="time">限时特惠</span>&nbsp;<em>￥</em>&nbsp;<span class="num">149</span></div>'],
	["id"=>'seven',"bigImage"=>'<img src="./assets/images/pic/r4-big1.jpg" alt=""><img class="img2" src="./assets/images/pic/r4-big2.jpg" alt="">',"smallImage"=>'<dd class="active"><img src="./assets/images/pic/r4-small1.jpg" alt=""></dd><dd><img src="./assets/images/pic/r4-small2.jpg" alt="">',"text"=>'<h2>乐心运动手环mambo HR 心率监测</h2><h3>心率检测，震动亮屏</h3><div class="price"><span class="time">限时特惠</span>&nbsp;<em>￥</em>&nbsp;<span class="num">199</span>&nbsp;<span class="start">起</span>'],
	["id"=>'nine',"bigImage"=>'<img src="./assets/images/pic/r6-big1.jpg" alt="">',"smallImage"=>'<dd class="active"><img src="./assets/images/pic/r6-small1.jpg" alt=""></dd>',"text"=>'<h2>暴风魔镜S1 虚拟现实智能VR眼镜 安卓版</h2><h4>支持3期免息</h4><div class="price"><em>￥</em>&nbsp;<span class="num">199</span></div>'],
	["id"=>'ten',"bigImage"=>'<img src="./assets/images/pic/r10-big1.jpg" alt="">',"smallImage"=>'<dd class="active"><img src="./assets/images/pic/r10-small1.jpg" alt=""></dd>',"text"=>'<h2>魅族手环</h2><h3>腕间流动的心率专家</h3><div class="price"><em>￥</em>&nbsp;<span class="num">229</span></div>'],
	["id"=>'eight',"bigImage"=>'<img src="./assets/images/pic/r7-big1.jpg" alt=""><img class="img2" src="./assets/images/pic/r7-big2.jpg" alt="">',"smallImage"=>'<dd class="active"><img src="./assets/images/pic/r7-small1.jpg" alt=""></dd><dd><img src="./assets/images/pic/r7-small2.jpg" alt="">',"text"=>'<h2>乐心心率手环ziva W</h2><h3>陈伟霆专属色 微信互联 来电提醒 即时消息</h3><div class="price"><em>￥</em>&nbsp;<span class="num">299</span></div>'],
	["id"=>'eleven',"bigImage"=>'<img src="./assets/images/pic/r11-big1.jpg" alt="">',"smallImage"=>'<dd class="active"><img src="./assets/images/pic/r11-small1.jpg" alt=""></dd>',"text"=>'<h2>乐心ziva连续心率监测运动手环</h2><h3>你的心跳 独一无二</h3><div class="price"><em>￥</em>&nbsp;<span class="num">299</span></div>'],
	["id"=>'six',"bigImage"=>'<img src="./assets/images/pic/r12-big1.jpg" alt="">',"smallImage"=>'<dd class="active"><img src="./assets/images/pic/r12-small1.jpg" alt=""></dd>',"text"=>'<h2>乐心mambo watch 触控大屏 动态心率监测</h2><h4>动态心率 实时监测 最高支持6期免息</h4><div class="price"><em>￥</em>&nbsp;<span class="num">399</span></div>'],
	["id"=>'one',"bigImage"=>'<img src="./assets/images/pic/r8-big1.jpg" alt=""><img class="img2" src="./assets/images/pic/r8-big2.jpg" alt="">',"smallImage"=>'<dd class="active"><img src="./assets/images/pic/r8-small1.jpg" alt=""></dd><dd><img src="./assets/images/pic/r8-small2.jpg" alt="">',"text"=>'<h2>乐心运动手环 ziva plus</h2><h3>乐心新品，震撼发布！专业运动 精于心率</h3><div class="price"><em>￥</em>&nbsp;<span class="num">499</span></div>'],
	["id"=>'thirtheen',"bigImage"=>'<img src="./assets/images/pic/r13-big1.jpg" alt=""><img class="img2" src="./assets/images/pic/r13-big2.jpg" alt="">',"smallImage"=>'<dd class="active"><img src="./assets/images/pic/r13-small1.jpg" alt=""></dd><dd><img src="./assets/images/pic/r13-small2.jpg" alt=""></dd>',"text"=>'<h2>Misfit Shine2智能手环 定制版</h2><h3>彩色LED 无需充电 魅族定制版</h3><div class="price"><em>￥</em>&nbsp;<span class="num">799</span></div>']
];

echo json_encode($arr);